name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Deploy to Server
      env:
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
      run: |
        mkdir -p ~/.ssh/
        echo ${{ secrets.SSH_PRIVATE_KEY }} > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        sed s/DUPA/\\n/g -i ~/.ssh/id_rsa
        scp -P $REMOTE_PORT -o "StrictHostKeyChecking no" -i ~/.ssh/id_rsa $GITHUB_WORKSPACE/main.py $REMOTE_USER@$REMOTE_HOST:$TARGET/
        scp -P $REMOTE_PORT -o "StrictHostKeyChecking no" -i ~/.ssh/id_rsa $GITHUB_WORKSPACE/Dockerfile $REMOTE_USER@$REMOTE_HOST:$TARGET/
        scp -P $REMOTE_PORT -o "StrictHostKeyChecking no" -i ~/.ssh/id_rsa $GITHUB_WORKSPACE/recreate.sh $REMOTE_USER@$REMOTE_HOST:$TARGET/
        ssh -p $REMOTE_PORT -o "StrictHostKeyChecking no" -i ~/.ssh/id_rsa $REMOTE_USER@$REMOTE_HOST "chmod 700 $TARGET/recreate.sh && $TARGET/recreate.sh"
