name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: echo 'dockering'
      #run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Server
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          #ARGS: "-i"
          #SOURCE: $GITHUB_WORKSPACE
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          #EXCLUDE: "/.github/"
      run: |
        echo $TARGET
        mkdir -p ~/.ssh/
        echo $SSH_PRIVATE_KEY > ~/.ssh/id_rsa
        chmod 700 ~/.ssh/id_rsa
        scp -P $REMOTE_PORT -o "StrictHostKeyChecking no" -i ~/.ssh/id_rsa $GITHUB_WORKSPACE/main.py $REMOTE_USER@$REMOTE_HOST:$TARGET/
        scp -P $REMOTE_PORT -o "StrictHostKeyChecking no" -i ~/.ssh/id_rsa $GITHUB_WORKSPACE/Dockerfile $REMOTE_USER@$REMOTE_HOST:$TARGET/
        scp -P $REMOTE_PORT -o "StrictHostKeyChecking no" -i ~/.ssh/id_rsa $GITHUB_WORKSPACE/recreate.sh $REMOTE_USER@$REMOTE_HOST:$TARGET/
        ssh -p $REMOTE_PORT -o "StrictHostKeyChecking no" -i ~/.ssh/id_rsa $REMOTE_USER@$REMOTE_HOST "chmod 700 $TARGET/recreate.sh && $TARGET/recreate.sh"
